# config path shortcuts go here , then iterate over each call , input, output with those? 
fornof.gifts.url:
  type: url                                                                                                                                                                                                     
  url: http://localhost:3000/
  method: POST
  headers: {}
  input_body_key: notes # this is what key to paste in
  command_for_body: '{notes: $notes}'
  input_file_type: json # yaml, json, text -- this is what type it is , only yaml to start.

fornof.mamlsocket: 
  type: file
  input_body_key: input.notes
  input_body_type: text
  input_file: $PATH\\target\\midi_split.txt # this is what will be populated with string or yaml dumps. 
  input_file_type: text # yaml, json 
  path: "C:\\projects\\music-user-reform\\MamlSocket"
  source_file: None # placeholder for sourcing things like venv and such. 
  call: "java -jar $PATH\\target\\MamlSocket-1.0-SNAPSHOT.jar -i $INPUT_FILE -o $OUTPUT_FILE"
  output_file: "c:\\web\\mid\\central_use.yml"

fornof.mid: 
  type: file
  input_body_key: path
  input_body_type: mid
  input_file: $PATH\\song.fornof.midi.mid # this is what will be populated with string or yaml dumps. 
  input_file_type: mid # yaml, json 
  path: "C:\\projects\\music-user-reform\\converter-midi" 
  call: "$PATH\\..\\venv\\Scripts\\python.exe $PATH\\MidiNBEF.py --input $INPUT_FILE --output $OUTPUT_FILE"  # $PATH\\..\\venv\\Scripts\\activate.bat;python 
  output_file: "$PATH\\song.fornof.midi.yml"

fornof.note_beat: 
  type: file
  input_body_key: input
  input_body_type: yaml
  input_file: $PATH\\song.fornof.note_beat.yaml # this is what will be populated with string or yaml dumps. 
  input_file_type: yaml # yaml, json 
  path: "C:\\projects\\music-user-reform\\converter-note-beats" 
  call: "$PATH\\..\\venv\\Scripts\\python.exe $PATH\\index.py --input $INPUT_FILE --output $OUTPUT_FILE"  # $PATH\\..\\venv\\Scripts\\activate.bat;python 
  output_file: "$PATH\\song.fornof.midi.yml"

# fornof.offset: 
#   type: file
#   input_body_key: input
#   input_body_type: yaml
#   input_file: $PATH\\song.fornof.offset.yaml # this is what will be populated with string or yaml dumps. 
#   input_file_type: yaml # yaml, json 
#   path: "C:\\projects\\music-user-reform\\converter-offset" 
#   call: "$PATH\\..\\venv\\Scripts\\python.exe $PATH\\index.py --input $INPUT_FILE --output $OUTPUT_FILE"  # $PATH\\..\\venv\\Scripts\\activate.bat;python 
#   output_file: "$PATH\\song.fornof.offset.output.yml"

fornof.offset:
  type: url                                                                                                                                                                                                     
  url: http://localhost:6881/nbef
  method: POST
  headers: {}
  input_body_key: input # this is what key to paste in
  input_body_type: yaml
  input_file_type: yaml # yaml, json, text -- this is what type it is , only yaml to start.


fornof.nbef: 
  type: nbef
  input_body_key: path